### ISSUE TITLE
execute函数里mysqli_query参数写反了

### ISSUE THREAD

**Issue by onlyquan** [sillydong/MySQL_DB_Diff#3]
参数写反了 应该把$connection和$sql换个位置：$result = @mysqli_query($connection,$sql);
别的没啥问题 使用了下 还不错。

**Comment by sillydong** [comment]
感谢指正，已修改

**Comment by onlyquan** [comment]
老哥  看你好几年没更新了，我以为你不维护了呢，没想到那么快你就改了，哈哈。

**Comment by sillydong** [comment]
因为好像也没啥要改的了😂
